In [1]:
import numpy as np
import pandas as pd

# Loading Data

In [2]:
df_train_origin = pd.read_csv('data/train.csv') # With Target
df_test_origin= pd.read_csv('data/test.csv') # No Target
df_train_origin.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [3]:
df_train_origin.dtypes

PassengerId         str
HomePlanet          str
CryoSleep        object
Cabin               str
Destination         str
Age             float64
VIP              object
RoomService     float64
FoodCourt       float64
ShoppingMall    float64
Spa             float64
VRDeck          float64
Name                str
Transported        bool
dtype: object

In [4]:
x = df_test_origin['Age']

# Removing Irrelevant Data

In [ ]:
def preprocessing_data(df):
    
    #? Removing Irrelevant Data
    df = df.drop(['PassengerId', 'Name'], axis=1)
    
    #? Feature Engineering Total Spendings
    spent_cols = [
    'RoomService',
    'FoodCourt',
    'ShoppingMall',
    'Spa',
    'VRDeck'
    ]
    
    # Replacing missing values with median
    fill_cols = spent_cols + ['Age']
    df[fill_cols] = df[fill_cols].fillna(df[fill_cols].median())
    
    df['TotalSpendings'] = df[spent_cols].sum(axis=1)
    
    #? Feature Engineering CabingDeck & CabinSide
    df['CabinDeck'] = df['Cabin'].str.split('/').str[0]
    df['CabinSide'] = df['Cabin'].str.split('/').str[2]
    df = df.drop('Cabin', axis=1)
    
    # Filling str & object missing values with 'Unknown'
    text_cols = [col for col in df.columns if df[col].dtype == 'str' or df[col].dtype == 'object']
    df[text_cols] = df[text_cols].fillna('Unknown')
    
    hot_encode_cols = [col for col in df.columns if df[col].dtype != 'float64' and col != 'Transported']
    
    df = pd.get_dummies(df, columns=hot_encode_cols, drop_first=True).astype(int)
    
    return df


df_train = preprocessing_data(df_train_origin)
df_test = preprocessing_data(df_test_origin)

print(df_train.shape, df_test.shape)
df_train.head()

(8693, 28) (4277, 27)

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,TotalSpendings,HomePlanet_Europa,HomePlanet_Mars,...,CabinDeck_B,CabinDeck_C,CabinDeck_D,CabinDeck_E,CabinDeck_F,CabinDeck_G,CabinDeck_T,CabinDeck_Unknown,CabinSide_S,CabinSide_Unknown
0,39,0,0,0,0,0,0,0,1,0,...,1,0,0,0,0,0,0,0,0,0
1,24,109,9,25,549,44,1,736,0,0,...,0,0,0,0,1,0,0,0,1,0
2,58,43,3576,0,6715,49,0,10383,1,0,...,0,0,0,0,0,0,0,0,1,0
3,33,0,1283,371,3329,193,0,5176,1,0,...,0,0,0,0,0,0,0,0,1,0
4,16,303,70,151,565,2,1,1091,0,0,...,0,0,0,0,1,0,0,0,1,0