In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as pltb
from sklearn.decomposition import PCA
from sklearn.preprocessing import OneHotEncoder

from utils import one_hot_encode

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1786629519.095969    4304 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1786629520.796825    4304 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1786629527.048531    4304 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.

In [2]:
df = pd.read_csv('Housing.csv')
print(df.shape)
df.head()

(545, 13)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

# Removing Irrelevant Data

In [3]:
df = df.drop(['basement', 'hotwaterheating', 'guestroom', 'mainroad', 'furnishingstatus'], axis=1)
df.head()

,price,area,bedrooms,bathrooms,stories,airconditioning,parking,prefarea
0,13300000,7420,4,2,3,yes,2,yes
1,12250000,8960,4,4,4,yes,3,no
2,12250000,9960,3,2,2,no,2,yes
3,12215000,7500,4,2,2,yes,3,yes
4,11410000,7420,4,1,2,yes,2,no

In [4]:
df.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'airconditioning',
       'parking', 'prefarea'],
      dtype='str')

# One Hot Encoding

In [5]:
columns_to_encode = ['airconditioning', 'prefarea']
df = one_hot_encode(df, *columns_to_encode)
df.head()

,price,area,bedrooms,bathrooms,stories,parking,airconditioning_no,airconditioning_yes,prefarea_no,prefarea_yes
0,13300000,7420,4,2,3,2,0.0,1.0,0.0,1.0
1,12250000,8960,4,4,4,3,0.0,1.0,1.0,0.0
2,12250000,9960,3,2,2,2,1.0,0.0,0.0,1.0
3,12215000,7500,4,2,2,3,0.0,1.0,0.0,1.0
4,11410000,7420,4,1,2,2,0.0,1.0,1.0,0.0

In [6]:
#TODO: turn encoder into a funciton, plot the data with pca, built & train the model
df_pca = PCA(n_components=2, copy=True, svd_solver='auto')